-- SELEECT, INSERT, UPDATE, DELETE

SELECT SUBSTR(STU_NAME, 2, 2) --2번째부터 2글자 가져와라.
FROM STUDENT;

SELECT *
FROM STUDENT;

SELECT *
FROM STUDENT
WHERE STU_GENDER = 'M' AND STU_DEPT = '전기전자';

SELECT *
FROM STUDENT
WHERE STU_HEIGHT >= 170;

SELECT *
FROM STUDENT
WHERE stu_height IS NULL; -- IS NOT NULL;

SELECT *
FROM STUDENT
WHERE SUBSTR(STU_NO, 3, 2) = 15;

SELECT * 
FROM STUDENT
ORDER BY STU_HEIGHT DESC; --오름차순

SELECT *
FROM STUDENT
ORDER BY STU_GRADE, STU_CLASS; --앞에꺼 먼저 정렬 -> 앞에꺼 정렬된 상태에서 뒤에꺼 정렬.

SELECT *
FROM STUDENT
WHERE stu_gender = 'M' --WHERE 절이 ORDER BY(정렬) 보다 먼저 나온다. WHERE 절로 한번 쳐내고 정렬.
ORDER BY stu_height;

SELECT STU_NO AS 학번, STU_NAME AS "학생 이름", STU_DEPT 학과 --AS, ""(쌍따옴표)생략 가능.
FROM STUDENT S;