--------------------------------------------------------
--  파일이 생성됨 - 수요일-2월-25-2026   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table TBL_FRUIT
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."TBL_FRUIT" 
   (	"NAME" VARCHAR2(30 BYTE), 
	"PRICE" NUMBER, 
	"COUNT" NUMBER
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table TBL_NOTE
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."TBL_NOTE" 
   (	"USERID" VARCHAR2(30 BYTE), 
	"QUIZ_ID" NUMBER, 
	"COUNTRY" VARCHAR2(100 BYTE), 
	"CAPITAL" VARCHAR2(100 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table TBL_QUIZ
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."TBL_QUIZ" 
   (	"QUIZ_ID" NUMBER, 
	"COUNTRY" VARCHAR2(100 BYTE), 
	"CAPITAL" VARCHAR2(100 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table TBL_STUDENT
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."TBL_STUDENT" 
   (	"STU_NO" CHAR(4 BYTE), 
	"STU_NAME" VARCHAR2(20 BYTE), 
	"STU_DEPT" VARCHAR2(50 BYTE), 
	"JAVA" NUMBER, 
	"ORACLE" NUMBER, 
	"HTML" NUMBER
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table TBL_USER
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."TBL_USER" 
   (	"USERID" VARCHAR2(30 BYTE), 
	"PWD" VARCHAR2(30 BYTE), 
	"USERNAME" VARCHAR2(30 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index TBL_FRUIT_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYSTEM"."TBL_FRUIT_PK" ON "SYSTEM"."TBL_FRUIT" ("NAME") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index TBL_NOTE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYSTEM"."TBL_NOTE_PK" ON "SYSTEM"."TBL_NOTE" ("QUIZ_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index SYS_C008365
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYSTEM"."SYS_C008365" ON "SYSTEM"."TBL_QUIZ" ("QUIZ_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index TBL_STUDENT_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYSTEM"."TBL_STUDENT_PK" ON "SYSTEM"."TBL_STUDENT" ("STU_NO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index SYS_C008335
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYSTEM"."SYS_C008335" ON "SYSTEM"."TBL_USER" ("USERID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table TBL_FRUIT
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."TBL_FRUIT" MODIFY ("NAME" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."TBL_FRUIT" ADD CONSTRAINT "TBL_FRUIT_PK" PRIMARY KEY ("NAME")
  USING INDEX "SYSTEM"."TBL_FRUIT_PK"  ENABLE;
--------------------------------------------------------
--  Constraints for Table TBL_NOTE
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."TBL_NOTE" MODIFY ("QUIZ_ID" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."TBL_NOTE" MODIFY ("USERID" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."TBL_NOTE" ADD CONSTRAINT "TBL_NOTE_PK" PRIMARY KEY ("QUIZ_ID")
  USING INDEX "SYSTEM"."TBL_NOTE_PK"  ENABLE;
--------------------------------------------------------
--  Constraints for Table TBL_QUIZ
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."TBL_QUIZ" MODIFY ("COUNTRY" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."TBL_QUIZ" MODIFY ("CAPITAL" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."TBL_QUIZ" ADD PRIMARY KEY ("QUIZ_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table TBL_STUDENT
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."TBL_STUDENT" MODIFY ("STU_NO" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."TBL_STUDENT" MODIFY ("STU_NAME" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."TBL_STUDENT" MODIFY ("STU_DEPT" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."TBL_STUDENT" ADD CONSTRAINT "TBL_STUDENT_PK" PRIMARY KEY ("STU_NO")
  USING INDEX "SYSTEM"."TBL_STUDENT_PK"  ENABLE;
--------------------------------------------------------
--  Constraints for Table TBL_USER
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."TBL_USER" MODIFY ("PWD" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."TBL_USER" MODIFY ("USERNAME" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."TBL_USER" ADD PRIMARY KEY ("USERID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
