--------------------------------------------------------
--  파일이 생성됨 - 목요일-2월-26-2026   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table DEPARTMENT
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."DEPARTMENT" 
   (	"DEPTNO" NUMBER(3,0), 
	"DNAME" VARCHAR2(25 BYTE), 
	"PART" NUMBER(3,0), 
	"BUILD" VARCHAR2(20 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table DEPT
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."DEPT" 
   (	"DEPTNO" NUMBER(2,0), 
	"DNAME" VARCHAR2(14 BYTE), 
	"LOC" VARCHAR2(13 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table EMP
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."EMP" 
   (	"EMPNO" NUMBER(4,0), 
	"ENAME" VARCHAR2(10 BYTE), 
	"JOB" VARCHAR2(9 BYTE), 
	"MGR" NUMBER(4,0), 
	"HIREDATE" DATE, 
	"SAL" NUMBER(7,2), 
	"COMM" NUMBER(7,2), 
	"DEPTNO" NUMBER(2,0)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table ENROL
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."ENROL" 
   (	"SUB_NO" CHAR(3 BYTE), 
	"STU_NO" CHAR(8 BYTE), 
	"ENR_GRADE" NUMBER
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table PROFESSOR
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."PROFESSOR" 
   (	"PROFNO" NUMBER(4,0), 
	"NAME" VARCHAR2(10 BYTE), 
	"ID" VARCHAR2(15 BYTE), 
	"POSITION" VARCHAR2(15 BYTE), 
	"PAY" NUMBER(3,0), 
	"HIREDATE" DATE, 
	"BONUS" NUMBER(4,0), 
	"DEPTNO" NUMBER(3,0), 
	"EMAIL" VARCHAR2(50 BYTE), 
	"HPAGE" VARCHAR2(50 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table SALGRADE
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."SALGRADE" 
   (	"GRADE" NUMBER, 
	"LOSAL" NUMBER, 
	"HISAL" NUMBER
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table STU
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."STU" 
   (	"STUNO" NUMBER(4,0), 
	"NAME" VARCHAR2(10 BYTE), 
	"ID" VARCHAR2(20 BYTE), 
	"GRADE" NUMBER, 
	"JUMIN" CHAR(13 BYTE), 
	"BIRTHDAY" DATE, 
	"TEL" VARCHAR2(15 BYTE), 
	"HEIGHT" NUMBER(4,0), 
	"WEIGHT" NUMBER(3,0), 
	"DEPTNO1" NUMBER(3,0), 
	"DEPTNO2" NUMBER(3,0), 
	"PROFNO" NUMBER(4,0)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table STUDENT
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."STUDENT" 
   (	"STU_NO" CHAR(8 BYTE), 
	"STU_NAME" VARCHAR2(12 BYTE), 
	"STU_DEPT" VARCHAR2(20 BYTE), 
	"STU_GRADE" NUMBER, 
	"STU_CLASS" CHAR(1 BYTE), 
	"STU_GENDER" CHAR(1 BYTE), 
	"STU_HEIGHT" NUMBER, 
	"STU_WEIGHT" NUMBER
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table SUBJECT
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."SUBJECT" 
   (	"SUB_NO" CHAR(3 BYTE), 
	"SUB_NAME" VARCHAR2(30 BYTE), 
	"SUB_PROF" VARCHAR2(12 BYTE), 
	"SUB_GRADE" NUMBER, 
	"SUB_DEPT" VARCHAR2(20 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table TBL_FRUIT
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."TBL_FRUIT" 
   (	"NAME" VARCHAR2(30 BYTE), 
	"PRICE" NUMBER, 
	"COUNT" NUMBER
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table TBL_NOTE
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."TBL_NOTE" 
   (	"USERID" VARCHAR2(30 BYTE), 
	"QUIZ_ID" NUMBER, 
	"COUNTRY" VARCHAR2(100 BYTE), 
	"CAPITAL" VARCHAR2(100 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table TBL_QUIZ
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."TBL_QUIZ" 
   (	"QUIZ_ID" NUMBER, 
	"COUNTRY" VARCHAR2(100 BYTE), 
	"CAPITAL" VARCHAR2(100 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table TBL_STUDENT
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."TBL_STUDENT" 
   (	"STU_NO" CHAR(4 BYTE), 
	"STU_NAME" VARCHAR2(20 BYTE), 
	"STU_DEPT" VARCHAR2(50 BYTE), 
	"JAVA" NUMBER, 
	"ORACLE" NUMBER, 
	"HTML" NUMBER
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table TBL_USER
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."TBL_USER" 
   (	"USERID" VARCHAR2(30 BYTE), 
	"PWD" VARCHAR2(30 BYTE), 
	"USERNAME" VARCHAR2(30 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index SYS_C008373
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYSTEM"."SYS_C008373" ON "SYSTEM"."DEPARTMENT" ("DEPTNO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C008371
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYSTEM"."SYS_C008371" ON "SYSTEM"."PROFESSOR" ("PROFNO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C008378
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYSTEM"."SYS_C008378" ON "SYSTEM"."STU" ("STUNO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C008379
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYSTEM"."SYS_C008379" ON "SYSTEM"."STU" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C008347
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYSTEM"."SYS_C008347" ON "SYSTEM"."STUDENT" ("STU_NO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index SYS_C008315
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYSTEM"."SYS_C008315" ON "SYSTEM"."SUBJECT" ("SUB_NO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index TBL_FRUIT_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYSTEM"."TBL_FRUIT_PK" ON "SYSTEM"."TBL_FRUIT" ("NAME") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index TBL_NOTE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYSTEM"."TBL_NOTE_PK" ON "SYSTEM"."TBL_NOTE" ("QUIZ_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index SYS_C008365
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYSTEM"."SYS_C008365" ON "SYSTEM"."TBL_QUIZ" ("QUIZ_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index TBL_STUDENT_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYSTEM"."TBL_STUDENT_PK" ON "SYSTEM"."TBL_STUDENT" ("STU_NO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index SYS_C008335
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYSTEM"."SYS_C008335" ON "SYSTEM"."TBL_USER" ("USERID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table DEPARTMENT
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."DEPARTMENT" MODIFY ("DNAME" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."DEPARTMENT" ADD PRIMARY KEY ("DEPTNO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table EMP
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."EMP" MODIFY ("EMPNO" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table PROFESSOR
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."PROFESSOR" MODIFY ("NAME" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."PROFESSOR" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."PROFESSOR" ADD PRIMARY KEY ("PROFNO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table STU
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."STU" MODIFY ("NAME" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."STU" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."STU" MODIFY ("JUMIN" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."STU" ADD CHECK (grade between 1 and 6) ENABLE;
  ALTER TABLE "SYSTEM"."STU" ADD PRIMARY KEY ("STUNO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "SYSTEM"."STU" ADD UNIQUE ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table STUDENT
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."STUDENT" ADD PRIMARY KEY ("STU_NO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table SUBJECT
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."SUBJECT" ADD PRIMARY KEY ("SUB_NO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table TBL_FRUIT
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."TBL_FRUIT" MODIFY ("NAME" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."TBL_FRUIT" ADD CONSTRAINT "TBL_FRUIT_PK" PRIMARY KEY ("NAME")
  USING INDEX "SYSTEM"."TBL_FRUIT_PK"  ENABLE;
--------------------------------------------------------
--  Constraints for Table TBL_NOTE
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."TBL_NOTE" MODIFY ("QUIZ_ID" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."TBL_NOTE" MODIFY ("USERID" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."TBL_NOTE" ADD CONSTRAINT "TBL_NOTE_PK" PRIMARY KEY ("QUIZ_ID")
  USING INDEX "SYSTEM"."TBL_NOTE_PK"  ENABLE;
--------------------------------------------------------
--  Constraints for Table TBL_QUIZ
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."TBL_QUIZ" MODIFY ("COUNTRY" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."TBL_QUIZ" MODIFY ("CAPITAL" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."TBL_QUIZ" ADD PRIMARY KEY ("QUIZ_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table TBL_STUDENT
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."TBL_STUDENT" MODIFY ("STU_NO" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."TBL_STUDENT" MODIFY ("STU_NAME" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."TBL_STUDENT" MODIFY ("STU_DEPT" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."TBL_STUDENT" ADD CONSTRAINT "TBL_STUDENT_PK" PRIMARY KEY ("STU_NO")
  USING INDEX "SYSTEM"."TBL_STUDENT_PK"  ENABLE;
--------------------------------------------------------
--  Constraints for Table TBL_USER
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."TBL_USER" MODIFY ("PWD" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."TBL_USER" MODIFY ("USERNAME" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."TBL_USER" ADD PRIMARY KEY ("USERID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table ENROL
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."ENROL" ADD FOREIGN KEY ("SUB_NO")
	  REFERENCES "SYSTEM"."SUBJECT" ("SUB_NO") ENABLE;
  ALTER TABLE "SYSTEM"."ENROL" ADD FOREIGN KEY ("STU_NO")
	  REFERENCES "SYSTEM"."STUDENT" ("STU_NO") ENABLE;
