-- 복습완료(+)
-- 검색,조회 => SELECT
SELECT * 
FROM STUDENT;

SELECT STU_NO, STU_NAME 
FROM STUDENT;

SELECT * 
FROM STUDENT
WHERE STU_HEIGHT >= 170 OR STU_GRADE = 1;

-- 수정 => UPDATE
UPDATE STUDENT SET
    STU_GRADE = 2,
    STU_HEIGHT = 180
WHERE STU_NO = '20153075';
COMMIT;
    
-- 삭제 => DELETE
DELETE FROM STUDENT 
WHERE STU_NO = '20131025';

-- 삽입 => INSERT
SELECT *
FROM STUDENT;

INSERT INTO STUDENT(STU_NO, STU_NAME, STU_DEPT)
VALUES('12341234', '홍길동', '기계');

INSERT INTO STUDENT
VALUES('12345678', '김철수', '전기전자', 1, 'A', 'M', NULL, 70);

INSERT INTO STUDENT
VALUES('12345678', '박영희', '전기전자', 1, 'A', 'F', NULL, 70);

INSERT INTO STUDENT
VALUES('12123434', '김철수', '전기전자', 1, 'A', 'M', NULL, 70);
COMMIT;

ROLLBACK;

UPDATE STUDENT SET STU_CLASS = 'D' WHERE STU_NO = '1';

INSERT INTO STUDENT(STU_NO, STU_NAME, STU_DEPT) VALUES('12345555', '김땡땡', '수선학과');
--ROLLBACK;


--SELECT * FROM ENROL;
--SELECT * FROM SUBJECT;