
CREATE TABLE TBL_QUIZ (
    QUIZ_ID      NUMBER PRIMARY KEY,
    COUNTRY      VARCHAR2(100) NOT NULL,
    CAPITAL      VARCHAR2(100) NOT NULL
);

SELECT * FROM TBL_QUIZ;
DROP SEQUENCE QUIZ_SEQ;

CREATE SEQUENCE QUIZ_SEQ
START WITH 1
INCREMENT BY 1
NOCACHE
NOCYCLE;

INSERT INTO TBL_QUIZ VALUES (QUIZ_SEQ.NEXTVAL, '대한민국', '서울');
INSERT INTO TBL_QUIZ VALUES (QUIZ_SEQ.NEXTVAL, '미국', '워싱턴DC');
INSERT INTO TBL_QUIZ VALUES (QUIZ_SEQ.NEXTVAL, '일본', '도쿄');
INSERT INTO TBL_QUIZ VALUES (QUIZ_SEQ.NEXTVAL, '중국', '베이징');
INSERT INTO TBL_QUIZ VALUES (QUIZ_SEQ.NEXTVAL, '영국', '런던');
INSERT INTO TBL_QUIZ VALUES (QUIZ_SEQ.NEXTVAL, '프랑스', '파리');
INSERT INTO TBL_QUIZ VALUES (QUIZ_SEQ.NEXTVAL, '독일', '베를린');
INSERT INTO TBL_QUIZ VALUES (QUIZ_SEQ.NEXTVAL, '이탈리아', '로마');
INSERT INTO TBL_QUIZ VALUES (QUIZ_SEQ.NEXTVAL, '캐나다', '오타와');
INSERT INTO TBL_QUIZ VALUES (QUIZ_SEQ.NEXTVAL, '호주', '캔버라');
INSERT INTO TBL_QUIZ VALUES (QUIZ_SEQ.NEXTVAL, '브라질', '브라질리아');
INSERT INTO TBL_QUIZ VALUES (QUIZ_SEQ.NEXTVAL, '러시아', '모스크바');
INSERT INTO TBL_QUIZ VALUES (QUIZ_SEQ.NEXTVAL, '스페인', '마드리드');
INSERT INTO TBL_QUIZ VALUES (QUIZ_SEQ.NEXTVAL, '인도', '뉴델리');
INSERT INTO TBL_QUIZ VALUES (QUIZ_SEQ.NEXTVAL, '멕시코', '멕시코시티');
INSERT INTO TBL_QUIZ VALUES (QUIZ_SEQ.NEXTVAL, '아르헨티나', '부에노스아이레스');
INSERT INTO TBL_QUIZ VALUES (QUIZ_SEQ.NEXTVAL, '이집트', '카이로');
INSERT INTO TBL_QUIZ VALUES (QUIZ_SEQ.NEXTVAL, '터키', '앙카라');
INSERT INTO TBL_QUIZ VALUES (QUIZ_SEQ.NEXTVAL, '태국', '방콕');
INSERT INTO TBL_QUIZ VALUES (QUIZ_SEQ.NEXTVAL, '베트남', '하노이');
INSERT INTO TBL_QUIZ VALUES (QUIZ_SEQ.NEXTVAL, '인도네시아', '자카르타');
INSERT INTO TBL_QUIZ VALUES (QUIZ_SEQ.NEXTVAL, '사우디아라비아', '리야드');
INSERT INTO TBL_QUIZ VALUES (QUIZ_SEQ.NEXTVAL, '남아프리카공화국', '프리토리아');
INSERT INTO TBL_QUIZ VALUES (QUIZ_SEQ.NEXTVAL, '스위스', '베른');
INSERT INTO TBL_QUIZ VALUES (QUIZ_SEQ.NEXTVAL, '네덜란드', '암스테르담');
INSERT INTO TBL_QUIZ VALUES (QUIZ_SEQ.NEXTVAL, '벨기에', '브뤼셀');
INSERT INTO TBL_QUIZ VALUES (QUIZ_SEQ.NEXTVAL, '스웨덴', '스톡홀름');
INSERT INTO TBL_QUIZ VALUES (QUIZ_SEQ.NEXTVAL, '노르웨이', '오슬로');
INSERT INTO TBL_QUIZ VALUES (QUIZ_SEQ.NEXTVAL, '그리스', '아테네');
INSERT INTO TBL_QUIZ VALUES (QUIZ_SEQ.NEXTVAL, '폴란드', '바르샤바');

SELECT * FROM TBL_QUIZ;
UPDATE TBL_QUIZ SET CAPITAL = '바르샤바' WHERE COUNTRY = '폴란드';

COMMIT;
ROLLBACK;
​
INSERT INTO TBL_QUIZ VALUES (QUIZ_SEQ.NEXTVAL, 'Z','H');
DELETE FROM TBL_QUIZ WHERE QUIZ_ID = 31;

--복사해서 쓰기--
SELECT *
FROM (
    SELECT *
    FROM TBL_QUIZ
    ORDER BY DBMS_RANDOM.VALUE
) WHERE ROWNUM <= 5;
