--
SELECT 
    ENAME, SAL,
    RANK() OVER (ORDER BY SAL DESC) AS RANK1,
    DENSE_RANK() OVER (ORDER BY SAL DESC) AS RANK2,
    ROW_NUMBER() OVER (ORDER BY SAL DESC, ENAME DESC) AS RANK3
FROM EMP;
--
SELECT
    ENAME, SAL, DEPTNO,
    RANK() OVER (PARTITION BY DEPTNO ORDER BY SAL DESC) AS RANK1
FROM EMP;
--
SELECT
    ENAME, SAL,
    RANK() OVER (ORDER BY SAL DESC) AS RANK1,
    DENSE_RANK() OVER (ORDER BY SAL DESC) AS RANK2,
    ROW_NUMBER() OVER (ORDER BY SAL DESC, ENAME DESC) AS RANK3 --SCOTT,FORD,CLARK
FROM EMP;
--
SELECT
    ENAME, SAL,
    RANK() OVER (ORDER BY SAL DESC) AS RANK1,
    DENSE_RANK() OVER (ORDER BY SAL DESC) AS RANK2,
    ROW_NUMBER() OVER (ORDER BY SAL DESC) AS RANK3 --CLARK,FORD,SCOTT
FROM EMP;
--
SELECT
    ENAME, SAL
FROM EMP;
--
SELECT 
    ENAME, SAL, DEPTNO,
    RANK() OVER (PARTITION BY DEPTNO ORDER BY SAL DESC) AS RANK1
FROM EMP;
--
SELECT 
    ENAME, SAL, DEPTNO,
    RANK() OVER (ORDER BY SAL DESC) AS RANK1
FROM EMP;
--
SELECT 
    ENAME, SAL, DEPTNO
FROM EMP;
--
SELECT * FROM EMP;