-- 셀프 조인(self join)

SELECT * FROM EMP;

SELECT *
FROM EMP E1
INNER JOIN EMP E2 ON E1.MGR = E2.EMPNO;  --E1.MGR를 기준으로 E2.EMPNO 인것들을 가져옴
                                         --E1테이블의 MGR를 기준으로 E2테이블의 EMPNO 인것들을 가져옴
--다시보기(+)
SELECT E1.EMPNO, E1.ENAME, E2.ENAME AS MANAGER
FROM EMP E1
INNER JOIN EMP E2 ON E1.MGR = E2.EMPNO;


SELECT *
FROM DEPARTMENT;

SELECT *
FROM PROFESSOR;

SELECT *
FROM PROFESSOR P
INNER JOIN DEPARTMENT D ON P.DEPTNO = D.DEPTNO;

SELECT PROFNO, NAME, DNAME
FROM PROFESSOR P
INNER JOIN DEPARTMENT D ON P.DEPTNO = D.DEPTNO;

SELECT PROFNO, NAME, DNAME
FROM PROFESSOR P
INNER JOIN DEPARTMENT D ON P.DEPTNO = D.DEPTNO;

SELECT *
FROM DEPARTMENT D1
INNER JOIN DEPARTMENT D2 ON D1.PART = D2.DEPTNO;


SELECT D1.DNAME, D2.DNAME
FROM DEPARTMENT D1
INNER JOIN DEPARTMENT D2 ON D1.PART = D2.DEPTNO;


SELECT PROFNO, NAME, D1.DNAME, D2.DNAME
FROM PROFESSOR P
INNER JOIN DEPARTMENT D1 ON P.DEPTNO = D1.DEPTNO
INNER JOIN DEPARTMENT D2 ON D1.PART = D2.DEPTNO;

--다시보기(+)
SELECT PROFNO, NAME, D1.DNAME, D2.DNAME, D3.DNAME
FROM PROFESSOR P
INNER JOIN DEPARTMENT D1 ON P.DEPTNO = D1.DEPTNO
INNER JOIN DEPARTMENT D2 ON D1.PART = D2.DEPTNO
INNER JOIN DEPARTMENT D3 ON D2.PART = D3.DEPTNO;