SELECT * FROM BOOK;
SELECT * FROM CUSTOMER;
SELECT * FROM ORDERS;

SELECT                     --첫번째 쿼리 위주로
    BOOKNAME, PUBLISHER
FROM BOOK
WHERE PRICE >= 10000
UNION
SELECT 
    BOOKNAME, PUBLISHER
FROM BOOK
WHERE PUBLISHER = '굿스포츠'
ORDER BY BOOKNAME;


-- 날짜별 수익
-- 날짜와 해당 시기의 판매 가격 출력

--
SELECT 날짜, SUM_SALEPRICE
FROM (
    SELECT 
        TO_CHAR(ORDERDATE, 'YYYY/MM/DD') AS 날짜,
        SUM(SALEPRICE) SUM_SALEPRICE,
        1 AS ORDERKEY
    FROM ORDERS
    GROUP BY ORDERDATE
    
    UNION
    SELECT 
        '매출총액',
        SUM(SALEPRICE),
        2 AS ORDERKEY
    FROM ORDERS
    ORDER BY ORDERKEY, SUM_SALEPRICE DESC
);

--
SELECT 
    TO_CHAR(ORDERDATE, 'YYYY/MM/DD') AS 날짜,
    SUM(SALEPRICE) SUM_SALEPRICE,
    1 AS ORDERKEY
FROM ORDERS
GROUP BY ORDERDATE
--
UNION
SELECT 
    '매출총액',
    SUM(SALEPRICE),
    2 AS ORDERKEY
FROM ORDERS
ORDER BY ORDERKEY, SUM_SALEPRICE;


--
SELECT TO_CHAR(ORDERDATE, 'YYYY/MM/DD') AS 날짜, SUM(SALEPRICE)
FROM ORDERS
GROUP BY ORDERDATE
--
UNION
SELECT '매출총액', SUM(SALEPRICE)
FROM ORDERS;

--
SELECT TO_CHAR(ORDERDATE, 'YYYY-MM-DD'), SUM(SALEPRICE)
FROM ORDERS
GROUP BY TO_CHAR(ORDERDATE, 'YYYY-MM-DD');


--
SELECT B.*, ROWNUM --눈에 안보여도 ROWNUM이 붙여지고있음.
FROM BOOK B
ORDER BY PRICE;  --처리순서 : ROWNUM -> ORDER BY  => 그래서 다른 속성기준으로  ORDER BY 하면 ROWNUM이 뒤죽박죽될수있음.
--                                               --ORDER BY는 데이터가 모두 뿌려진후 정렬되는것임
SELECT B.*, ROWNUM 
FROM BOOK B
WHERE ROWNUM = 3; -- 레코드가 한줄씩 생성되면서 ROWNUM이 붙여진다. **

-- 책 가격이 가장 높은 상위 3개의 책이름, 가격 출력
SELECT * FROM BOOK;
--
SELECT BOOKNAME, PRICE , ROWNUM
FROM (
    SELECT *
    FROM BOOK
    ORDER BY PRICE DESC
) WHERE ROWNUM <= 3;


--
SELECT *
FROM BOOK
ORDER BY PRICE DESC;

--
SELECT * FROM CUSTOMER;
SELECT * FROM ORDERS;

--
SELECT B.*, ROWNUM 
FROM BOOK B
WHERE ROWNUM <= 3
ORDER BY PRICE DESC;

-- 
SELECT * 
FROM BOOK
WHERE BOOKNAME LIKE '%축구%'; -- 포함된거는 LIKE

-- CASE ~ WHEN
-- 날짜별 매출

-- 날짜, 해당 날짜의 매출,
-- 매출이 20000 이상일 경우 '상', 10000 이상일 경우 '중'
-- 그외는 '하'로 표기

SELECT * 
FROM ORDERS;
--

SELECT 
    TO_CHAR(ORDERDATE, 'YY/MM/DD'),
    SUM(SALEPRICE),
    CASE
        WHEN SUM(SALEPRICE) >= 20000 THEN '상'  --WHEN(조건절)THEN(행에 표시)
        WHEN SUM(SALEPRICE) >= 10000 THEN '중'
        ELSE '하'
    END 상중하
FROM ORDERS
GROUP BY TO_CHAR(ORDERDATE, 'YY/MM/DD');
--




