-- BOOK, CUSTOMER, ORDERS
SELECT * FROM BOOK;
SELECT * FROM CUSTOMER;
SELECT * FROM ORDERS;
--1. BOOK 테이블에서 PRICE 가 20000 이상인 레코드를 출력하시오.
SELECT * 
FROM BOOK
WHERE PRICE >= 20000;

--2. BOOK 테이블에서 BOOKNAME 컬럼에 '야구' 가 들어간 레코드 출력하시오.
SELECT *
FROM BOOK
WHERE BOOKNAME LIKE '%야구%';

--3. BOOK 테이블에서 PUBLISHER 컬럼이 '굿스포츠'인 데이터를 BOOKNAME 컬럼 내림차순으로 출력하시오.
SELECT *
FROM BOOK
WHERE PUBLISHER = '굿스포츠'
ORDER BY BOOKNAME DESC;

--4. BOOK 테이블에서 PRICE 가 5000이상 20000이하 데이터 출력하시오.
SELECT *
FROM BOOK
WHERE PRICE BETWEEN 5000 AND 20000;

--5. CUSTOMER 테이블에서 PHONE가 NULL이 아니고 CUSTID가 3이상인 레코드 출력하시오.
SELECT *
FROM CUSTOMER
WHERE PHONE IS NOT NULL AND CUSTID >= 3;


--6. 고객별 평균 주문 금액을 반올림한 값을 출력하시오.(고객명, 평균 주문 금액 출력)
SELECT *
FROM CUSTOMER;
SELECT *
FROM ORDERS;
-- 답변:
SELECT NAME, ROUND(AVG(SALEPRICE))
FROM (
    SELECT *
    FROM CUSTOMER C
    INNER JOIN ORDERS O ON C.CUSTID = O.CUSTID
)
GROUP BY NAME;

--
SELECT *
FROM CUSTOMER C
INNER JOIN ORDERS O ON C.CUSTID = O.CUSTID;


--7. 이상미디어의 책을 구매한 고객 중에서 같은 성(姓)을 가진 사람이 몇 명이나 되는지 성별 인원수를 구하시오.
    --> 같은사람이어도 중복 카운트해도되나? (X)
SELECT *
FROM BOOK;
SELECT *
FROM CUSTOMER;
SELECT *
FROM ORDERS;
-- 답변 :
SELECT SUBSTR(NAME,1, 1)AS 같은성씨 , COUNT(*)  --같은성씨별 행의수 (추그룹별 행의수=같은성씨 사람수)
FROM (
    SELECT C.CUSTID, NAME
    FROM CUSTOMER C
    INNER JOIN ORDERS O ON C.CUSTID = O.CUSTID
    INNER JOIN BOOK B ON O.BOOKID = B.BOOKID
    WHERE PUBLISHER = '이상미디어'
    GROUP BY C.CUSTID, NAME
)
GROUP BY SUBSTR(NAME,1, 1) ;

--
SELECT C.CUSTID, NAME
FROM CUSTOMER C
INNER JOIN ORDERS O ON C.CUSTID = O.CUSTID
INNER JOIN BOOK B ON O.BOOKID = B.BOOKID
WHERE PUBLISHER = '이상미디어'
GROUP BY C.CUSTID, NAME;
--
SELECT *
FROM CUSTOMER C
INNER JOIN ORDERS O ON C.CUSTID = O.CUSTID
INNER JOIN BOOK B ON O.BOOKID = B.BOOKID
WHERE PUBLISHER = '이상미디어';
--
SELECT *
FROM CUSTOMER C
INNER JOIN ORDERS O ON C.CUSTID = O.CUSTID
INNER JOIN BOOK B ON O.BOOKID = B.BOOKID;


--8. 이상미디어에서 2020년 7월 7일에 주문받은 도서의 주문번호, 주문일, 고객이름, 도서번호를 모두 보이시오. 
SELECT *
FROM CUSTOMER C
INNER JOIN ORDERS O ON C.CUSTID = O.CUSTID
INNER JOIN BOOK B ON O.BOOKID = B.BOOKID;
--
SELECT ORDERID, ORDERDATE, NAME, B.BOOKID
FROM CUSTOMER C
INNER JOIN ORDERS O ON C.CUSTID = O.CUSTID
INNER JOIN BOOK B ON O.BOOKID = B.BOOKID
WHERE PUBLISHER = '이상미디어' AND ORDERDATE = TO_DATE('20/07/07');

--9. 이름, 전화번호가 포함된 고객목록을 보이시오. 단, 전화번호가 없는 고객은 ‘연락처없음’으로 표시하시오.

SELECT NAME, NVL(PHONE, '연락처없음')
FROM CUSTOMER;

--10. 전체 평균 주문금액 보다 금액이 작은 주문에 대해서 주문번호와 금액을 출력하시오.

SELECT *
FROM ORDERS;
-- 답변 : 
SELECT ORDERID, SALEPRICE
FROM ORDERS
WHERE SALEPRICE < (
    SELECT AVG(SALEPRICE) --RETURN:11800
    FROM ORDERS
);

--
SELECT AVG(SALEPRICE) --RETURN:11800
FROM ORDERS;

--11. ‘대한민국’에 거주하는 고객에게 판매한 도서의 총 판매액을 출력하시오.
SELECT *
FROM CUSTOMER;
SELECT *
FROM ORDERS;
-- 답변 :
SELECT SUM(SALEPRICE)
FROM CUSTOMER C
INNER JOIN ORDERS O ON C.CUSTID = O.CUSTID
WHERE ADDRESS LIKE '%대한민국%';

--
SELECT *
FROM CUSTOMER C
INNER JOIN ORDERS O ON C.CUSTID = O.CUSTID;


--12. 3번 고객이 주문한 도서의 최고 금액보다 더 비싼 도서를 구입한 주문의 주문번호와 금액을 출력하시오.

SELECT *
FROM CUSTOMER;
SELECT *
FROM ORDERS;
-- 답변 :
SELECT ORDERID, SALEPRICE
FROM ORDERS
WHERE SALEPRICE > (
    SELECT MAX(SALEPRICE)
    FROM ORDERS
    GROUP BY CUSTID
    HAVING CUSTID = 3
);
--3번 고객이 주문한 도서의 최고 금액--13000
SELECT MAX(SALEPRICE)
FROM ORDERS
GROUP BY CUSTID
HAVING CUSTID = 3;


--13. 이상미디어의 고객별 판매액을 보이시오(고객이름과 고객별 판매액 출력).

SELECT *
FROM CUSTOMER;
SELECT *
FROM ORDERS;
SELECT *
FROM BOOK;
-- 답변 :
SELECT NAME, SUM(SALEPRICE)
FROM CUSTOMER C
INNER JOIN ORDERS O ON C.CUSTID = O.CUSTID
INNER JOIN BOOK B ON O.BOOKID = B.BOOKID
WHERE PUBLISHER = '이상미디어'
GROUP BY NAME;
--
SELECT *
FROM CUSTOMER C
INNER JOIN ORDERS O ON C.CUSTID = O.CUSTID
INNER JOIN BOOK B ON O.BOOKID = B.BOOKID;


-- EMP, DEPT, SALGRADE
SELECT *
FROM EMP;
SELECT *
FROM DEPT;
SELECT *
FROM SALGRADE;
-- **JOIN이 먼저 수행되어 데이터를 결합한 후, 그 결과에 대해 GROUP BY가 실행

--1. 각 부서별 급여 평균 등급을 출력하시오.(평균 급여 등급, 부서명 출력)
--답변 :
SELECT DNAME, AVG(GRADE)
FROM EMP E
INNER JOIN SALGRADE S ON SAL BETWEEN LOSAL AND HISAL
INNER JOIN DEPT D ON E.DEPTNO = D.DEPTNO
GROUP BY D.DEPTNO, DNAME;

--
SELECT E.*, DNAME, GRADE
FROM EMP E
INNER JOIN SALGRADE S ON SAL BETWEEN LOSAL AND HISAL
INNER JOIN DEPT D ON E.DEPTNO = D.DEPTNO;

--2. 자신의 매니저(MGR)가 받는 급여 등급과 본인이 받는 급여 등급의 차이를 구하시오.
SELECT *
FROM EMP;
SELECT *
FROM DEPT;
SELECT *
FROM SALGRADE;
-- 답변 :
SELECT S2.GRADE, S.GRADE, E.ENAME, ABS(S2.GRADE - S.GRADE) 
FROM EMP E
INNER JOIN SALGRADE S ON E.SAL BETWEEN S.LOSAL AND S.HISAL
INNER JOIN EMP E2 ON E.MGR = E2.EMPNO
INNER JOIN SALGRADE S2 ON E2.SAL BETWEEN S2.LOSAL AND S2.HISAL;
--
SELECT *
FROM EMP E
INNER JOIN SALGRADE S ON E.SAL BETWEEN S.LOSAL AND S.HISAL
INNER JOIN EMP E2 ON E.MGR = E2.EMPNO
INNER JOIN SALGRADE S2 ON E2.SAL BETWEEN S2.LOSAL AND S2.HISAL;
--
SELECT *
FROM EMP E
INNER JOIN SALGRADE S ON SAL BETWEEN LOSAL AND HISAL
INNER JOIN EMP E2 ON E.MGR = E2.EMPNO;
--
SELECT E.*, GRADE
FROM EMP E
INNER JOIN SALGRADE S ON SAL BETWEEN LOSAL AND HISAL;

--3. 본인 부서의 평균 급여보다 높은 급여를 받는 사람의 이름, 부서명, 급여, 본인부서의 평균급여를 출력하시오.
SELECT *
FROM EMP;
SELECT *
FROM DEPT;
-- 답변 : 
SELECT ENAME, DNAME, SAL, ROUND(AVG_SAL)
FROM EMP E
INNER JOIN DEPT D ON E.DEPTNO = D.DEPTNO
INNER JOIN (
    SELECT DEPTNO, AVG(SAL) AVG_SAL
    FROM EMP
    GROUP BY DEPTNO
) T ON D.DEPTNO = T.DEPTNO
WHERE SAL > AVG_SAL;
--
SELECT DEPTNO, AVG(SAL)
FROM EMP
GROUP BY DEPTNO;

-- TBL_USER, TBL_BOARD, TBL_COMMNET
--1. 댓글을 가장 많이 쓴 사용자의 이름, 댓글 개수를 출력하시오.
SELECT *
FROM TBL_USER;
SELECT *
FROM TBL_BOARD;
SELECT *
FROM TBL_COMMENT;

-- 여기부터 수업~(+)
SELECT T.USERID, USERNAME, CNT
FROM (
    SELECT USERID, COUNT(*) CNT
    FROM TBL_COMMENT
    GROUP BY USERID
) T
INNER JOIN TBL_USER U ON T.USERID = U.USERID
WHERE CNT = (
    SELECT MAX(CNT)   --7
    FROM (
        SELECT USERID, COUNT(*) CNT
        FROM TBL_COMMENT
        GROUP BY USERID
    )
);

--
SELECT *
FROM (
    SELECT USERID, COUNT(*) CNT
    FROM TBL_COMMENT
    GROUP BY USERID
)
WHERE CNT = (
    SELECT MAX(CNT)   --7
    FROM (
        SELECT USERID, COUNT(*) CNT
        FROM TBL_COMMENT
        GROUP BY USERID
    )
);
-- 정답 :
SELECT C.USERID, USERNAME,COUNT(*)
FROM TBL_COMMENT C
INNER JOIN TBL_USER U ON C.USERID = U.USERID
GROUP BY C.USERID, USERNAME
HAVING COUNT(*) = (
    SELECT MAX(COUNT(*)) --7
    FROM TBL_COMMENT
    GROUP BY USERID
);
--
SELECT MAX(COUNT(*)) --7
FROM TBL_COMMENT
GROUP BY USERID;

--
SELECT MAX(CNT)   --7
FROM (
    SELECT USERID, COUNT(*) CNT
    FROM TBL_COMMENT
    GROUP BY USERID
);
--
SELECT *
FROM (
    SELECT USERID, COUNT(*) CNT
    FROM TBL_COMMENT
    GROUP BY USERID
);

--
SELECT USERID, COUNT(*) CNT
FROM TBL_COMMENT
GROUP BY USERID;

-- 답변:
SELECT USERNAME, CNT
FROM (
    SELECT 
        USERNAME,
        COUNT(*) CNT,
        1 AS ORDERKEY
    FROM TBL_USER U
    INNER JOIN TBL_COMMENT C ON U.USERID = C.USERID
    GROUP BY USERNAME
    ORDER BY COUNT(*) DESC
)
WHERE CNT = (
    SELECT MAX(CNT)  -- 7
    FROM (
        SELECT 
            USERNAME,
            COUNT(*) CNT,
            1 AS ORDERKEY
        FROM TBL_USER U
        INNER JOIN TBL_COMMENT C ON U.USERID = C.USERID
        GROUP BY USERNAME
        ORDER BY COUNT(*) DESC
    )
    GROUP BY ORDERKEY
);
--
SELECT 
    USERNAME,
    COUNT(*) CNT,
    1 AS ORDERKEY
FROM TBL_USER U
INNER JOIN TBL_COMMENT C ON U.USERID = C.USERID
GROUP BY USERNAME
ORDER BY COUNT(*) DESC;


--
SELECT MAX(CNT)  -- 7
FROM (
    SELECT 
        USERNAME,
        COUNT(*) CNT,
        1 AS ORDERKEY
    FROM TBL_USER U
    INNER JOIN TBL_COMMENT C ON U.USERID = C.USERID
    GROUP BY USERNAME
    ORDER BY COUNT(*) DESC
)
GROUP BY ORDERKEY;
--
SELECT 
    USERNAME,
    COUNT(*) CNT,
    1 AS ORDERKEY
FROM TBL_USER U
INNER JOIN TBL_COMMENT C ON U.USERID = C.USERID
GROUP BY USERNAME
ORDER BY COUNT(*) DESC;
--
SELECT 
    C.USERID,
    COUNT(*)
FROM TBL_USER U
INNER JOIN TBL_COMMENT C ON U.USERID = C.USERID
GROUP BY C.USERID;
--
SELECT C.USERID, COUNT(*)
FROM TBL_USER U
INNER JOIN TBL_COMMENT C ON U.USERID = C.USERID
GROUP BY C.USERID;
--
SELECT *
FROM TBL_USER U
INNER JOIN TBL_COMMENT C ON U.USERID = C.USERID;


--2. 각 사용자가 작성한 게시글의 작성자 이름, 조회수 평균을 구하시오. 
-- 단, 작성글이 없으면 조회수 평균에 '게시글 없음'으로 출력하시오.
SELECT *
FROM TBL_USER;
SELECT *
FROM TBL_BOARD;
SELECT *
FROM TBL_COMMENT;
-- 답변 : --> 일단 작성하긴했는데 한번만 더 흐름따라가기 ㄱㄱ(+)
SELECT USERNAME, NVL(TO_CHAR(ROUND(AVG(CNT),1)), '게시글 없음')
FROM TBL_USER U
LEFT JOIN TBL_BOARD B ON B.USERID = U.USERID
GROUP BY U.USERID, USERNAME;
--
SELECT *
FROM TBL_USER U
LEFT JOIN TBL_BOARD B ON B.USERID = U.USERID;
--
SELECT U.USERNAME, AVG(CNT)
FROM TBL_BOARD B
INNER JOIN TBL_USER U ON B.USERID = U.USERID
GROUP BY U.USERID, U.USERNAME; --
--
SELECT *
FROM TBL_BOARD B
INNER JOIN TBL_USER U ON B.USERID = U.USERID;

