SELECT * FROM STUDENT;
SELECT * FROM ENROL;
SELECT * FROM SUBJECT;

-- STUDENT, ENROL, SUBJECT 
-- 1. 성이 '김'씨인 학생들의 학번, 이름, 학과를 출력하시오.
SELECT STU_NO,STU_NAME,STU_DEPT 
FROM STUDENT;

-- 2. 15학번 학생들의 학번, 이름, 학과를 출력하시오.
SELECT * FROM STUDENT;
--
SELECT STU_NO, STU_NAME, STU_DEPT
FROM STUDENT
WHERE SUBSTR(STU_NO,1,4) = '2015';

-- 3. 컴퓨터정보 학과 학생들의 시험 평균 점수를 구하시오.
SELECT * FROM STUDENT;
SELECT * FROM ENROL;
-- 답변 : 
SELECT AVG(ENR_GRADE)  --69.4
FROM STUDENT S
LEFT JOIN ENROL E ON S.STU_NO = E.STU_NO
WHERE STU_DEPT = '컴퓨터정보';
--
SELECT *
FROM STUDENT S
LEFT JOIN ENROL E ON S.STU_NO = E.STU_NO
WHERE STU_DEPT = '컴퓨터정보';

-- 4. 컴퓨터개론 수업을 듣는 학생의 학번, 이름, 학과, 시험점수를 구하시오.
SELECT * FROM STUDENT;
SELECT * FROM ENROL;
SELECT * FROM SUBJECT;
-- 답변:
SELECT S.STU_NO, STU_NAME, STU_DEPT, ENR_GRADE
FROM STUDENT S
INNER JOIN ENROL E ON S.STU_NO = E.STU_NO
INNER JOIN SUBJECT SUB ON E.SUB_NO = SUB.SUB_NO
WHERE SUB_NAME = '컴퓨터개론';

-- 5. 학생들의 전체 평균 키보다 큰 키를 가진 학생들의 학번, 이름, 키를 출력하시오.
SELECT * FROM STUDENT;
--
SELECT STU_NO, STU_NAME, STU_HEIGHT
FROM STUDENT
WHERE STU_HEIGHT > (
    SELECT AVG(STU_HEIGHT) --170.125
    FROM STUDENT
);

--
SELECT AVG(STU_HEIGHT) --170.125
FROM STUDENT;


-- 6. 본인 학과의 평균 키보다 큰 학생들의 이름, 학과, 키, 학과 평균키 값 출력
SELECT * FROM STUDENT;
-- 답변 :
SELECT STU_NAME, S.STU_DEPT, STU_HEIGHT, AVG_HEIGHT
FROM STUDENT S
INNER JOIN (
    SELECT STU_DEPT, AVG(STU_HEIGHT) AVG_HEIGHT
    FROM STUDENT
    GROUP BY STU_DEPT
) T ON S.STU_DEPT = T.STU_DEPT
WHERE STU_HEIGHT > AVG_HEIGHT;

--
SELECT STU_DEPT, AVG(STU_HEIGHT)
FROM STUDENT
GROUP BY STU_DEPT;

-- EMP, SALGRADE, DEPT
SELECT * FROM EMP;
SELECT * FROM SALGRADE;
SELECT * FROM DEPT;

-- 1. 급여 등급이 3이상인 사원의 사번, 이름, 급여등급을 출력하시오.
SELECT EMPNO, ENAME, GRADE
FROM EMP E
INNER JOIN SALGRADE S ON SAL BETWEEN LOSAL AND HISAL
WHERE GRADE >= 3;

-- 2. 사번, 이름, 팀장(MGR)의 이름을 출력하시오.
SELECT * FROM EMP;
-- 답변 :
SELECT E1.EMPNO, E1.ENAME, E2.ENAME 
FROM EMP E1 
INNER JOIN EMP E2 ON E1.MGR = E2.EMPNO;

--
SELECT * 
FROM EMP E1 
INNER JOIN EMP E2 ON E1.MGR = E2.EMPNO;

-- 3. 부서별 가장 높은 급여를 받는 사원의 사번, 이름, 급여, 부서명을 출력하시오.
SELECT * FROM EMP;
SELECT * FROM SALGRADE;
SELECT * FROM DEPT;
-- 답변 :
SELECT EMPNO,ENAME,SAL,DNAME
FROM EMP E
INNER JOIN DEPT D ON E.DEPTNO = D.DEPTNO
WHERE (E.DEPTNO, SAL) IN (
    SELECT DEPTNO, MAX(SAL) MAX_SAL  --(20,3000),(30,2850),(10,5000)
    FROM EMP E
    GROUP BY DEPTNO
);

--
SELECT *
FROM EMP E
INNER JOIN DEPT D ON E.DEPTNO = D.DEPTNO;
--
SELECT DEPTNO, MAX(SAL) MAX_SAL  --(20,3000),(30,2850),(10,5000)
FROM EMP E
GROUP BY DEPTNO;

--
SELECT * 
FROM EMP E
INNER JOIN DEPT D ON E.DEPTNO = D.DEPTNO;

-- 4. 입사년도가 1981년도인 사원들의 급여 총합을 구하시오.
SELECT * FROM EMP;
-- 답변 :
SELECT SUM(SAL)
FROM EMP
WHERE SUBSTR(TO_CHAR(HIREDATE, 'YYMMDD'), 1, 2) = '81';

--
SELECT *
FROM EMP
WHERE SUBSTR(TO_CHAR(HIREDATE, 'YYMMDD'), 1, 2) = '81';
--
SELECT 
    TO_CHAR(HIREDATE, 'YYMMDD')
FROM EMP;

-- STU, PROFESSOR, DEPARTMENT
SELECT * FROM STU;
SELECT * FROM PROFESSOR;
SELECT * FROM DEPARTMENT;

-- 1. 남자이면서(주민번호 7번째자리 1) 공과대학에 속한 학생의 수를 구하시오.

SELECT * FROM STU;
-- 답변 : 
SELECT COUNT(*)
FROM STU S
INNER JOIN DEPARTMENT D1 ON S.DEPTNO1 = D1.DEPTNO
INNER JOIN DEPARTMENT D2 ON D1.PART = D2.DEPTNO
INNER JOIN DEPARTMENT D3 ON D2.PART = D3.DEPTNO
WHERE SUBSTR(JUMIN, 7, 1) = '1' AND D3.DEPTNO = 10;
--
SELECT * 
FROM STU S
INNER JOIN DEPARTMENT D1 ON S.DEPTNO1 = D1.DEPTNO
INNER JOIN DEPARTMENT D2 ON D1.PART = D2.DEPTNO
INNER JOIN DEPARTMENT D3 ON D2.PART = D3.DEPTNO;

-- 2. 학생들의 아이디의 마지막 세글자를 '*' 로 채우시오
SELECT * FROM STU;
-- 답변 :
SELECT
    --SUBSTR(ID,1, LENGTH(ID)-3),
    RPAD(SUBSTR(ID,1, LENGTH(ID)-3), LENGTH(ID), '*')
FROM STU;

-- 3. 보너스+급여가 400 이하인 교수들의 이름, 아이디, 학과명을 출력하시오.

SELECT * FROM PROFESSOR;
SELECT * FROM DEPARTMENT;
--
SELECT NAME, ID, DNAME
FROM PROFESSOR P
INNER JOIN DEPARTMENT D ON P.DEPTNO = D.DEPTNO
WHERE PAY + BONUS <= 400;

-- 4. 담당 학생이 2명이상인 교수의 이름, 아이디, 담당학생 수를 출력하시오.
SELECT * FROM STU;
SELECT * FROM PROFESSOR;
SELECT * FROM DEPARTMENT;
-- 답변 :
SELECT NAME, ID, CNT
FROM PROFESSOR P
INNER JOIN (
    SELECT S.PROFNO, COUNT(*) CNT
    FROM STU S
    INNER JOIN PROFESSOR P ON S.PROFNO = P.PROFNO
    GROUP BY S.PROFNO
    HAVING COUNT(*) >= 2
) T ON P.PROFNO = T.PROFNO; 

--
SELECT *
FROM PROFESSOR P
INNER JOIN (
    SELECT S.PROFNO, COUNT(*)
    FROM STU S
    INNER JOIN PROFESSOR P ON S.PROFNO = P.PROFNO
    GROUP BY S.PROFNO
    HAVING COUNT(*) >= 2
) T ON P.PROFNO = T.PROFNO; 

--
SELECT S.PROFNO, COUNT(*)
FROM STU S
INNER JOIN PROFESSOR P ON S.PROFNO = P.PROFNO
GROUP BY S.PROFNO
HAVING COUNT(*) >= 2;
--
SELECT S.PROFNO, COUNT(*)
FROM STU S
INNER JOIN PROFESSOR P ON S.PROFNO = P.PROFNO
GROUP BY S.PROFNO;
--
SELECT *
FROM STU S
INNER JOIN PROFESSOR P ON S.PROFNO = P.PROFNO;

-- EMP, SALGRADE, DEPT
-- 1. ALLEN과 같은 JOB, DEPTNO(부서)를 가진 사람을 구하시오.(ENAME, DNAME 출력)
SELECT * FROM EMP;
SELECT * FROM SALGRADE;
SELECT * FROM DEPT;
-- 답변 : 
SELECT ENAME, DNAME
FROM EMP E
INNER JOIN DEPT D ON E.DEPTNO = D.DEPTNO
WHERE (JOB, D.DEPTNO) = (
    SELECT JOB, D.DEPTNO
    FROM EMP
    WHERE ENAME = 'ALLEN'
);
--
SELECT JOB, DEPTNO   --('SALESMAN',30)
FROM EMP
WHERE ENAME = 'ALLEN';

-- 2. 자신의 부서 급여등급 평균보다 높은 등급인 사람의 이름, 부서명, 급여등급을 구하시오.
SELECT * FROM EMP;
SELECT * FROM SALGRADE;
SELECT * FROM DEPT;

--

SELECT ENAME, DNAME, GRADE
FROM EMP E
INNER JOIN DEPT D ON E.DEPTNO = D.DEPTNO
INNER JOIN SALGRADE S ON SAL BETWEEN LOSAL AND HISAL
INNER JOIN (
    SELECT E.DEPTNO, AVG(GRADE) AVG_GRADE
    FROM EMP E
    INNER JOIN DEPT D ON E.DEPTNO = D.DEPTNO
    INNER JOIN SALGRADE S ON SAL BETWEEN LOSAL AND HISAL
    GROUP BY E.DEPTNO
) T ON D.DEPTNO = T.DEPTNO
WHERE GRADE > AVG_GRADE; 
--
SELECT * 
FROM EMP E
INNER JOIN DEPT D ON E.DEPTNO = D.DEPTNO
INNER JOIN SALGRADE S ON SAL BETWEEN LOSAL AND HISAL
INNER JOIN (
    SELECT E.DEPTNO, AVG(GRADE) AVG_GRADE
    FROM EMP E
    INNER JOIN DEPT D ON E.DEPTNO = D.DEPTNO
    INNER JOIN SALGRADE S ON SAL BETWEEN LOSAL AND HISAL
    GROUP BY E.DEPTNO
) T ON D.DEPTNO = T.DEPTNO
WHERE GRADE > AVG_GRADE; 

--
SELECT * 
FROM EMP E
INNER JOIN DEPT D ON E.DEPTNO = D.DEPTNO
INNER JOIN SALGRADE S ON SAL BETWEEN LOSAL AND HISAL
INNER JOIN (
    SELECT E.DEPTNO, AVG(GRADE)
    FROM EMP E
    INNER JOIN DEPT D ON E.DEPTNO = D.DEPTNO
    INNER JOIN SALGRADE S ON SAL BETWEEN LOSAL AND HISAL
    GROUP BY E.DEPTNO
) T ON D.DEPTNO = T.DEPTNO; 

--
SELECT E.DEPTNO, AVG(GRADE)
FROM EMP E
INNER JOIN DEPT D ON E.DEPTNO = D.DEPTNO
INNER JOIN SALGRADE S ON SAL BETWEEN LOSAL AND HISAL
GROUP BY E.DEPTNO; 
--
SELECT * 
FROM EMP E
INNER JOIN DEPT D ON E.DEPTNO = D.DEPTNO
INNER JOIN SALGRADE S ON SAL BETWEEN LOSAL AND HISAL; 
--
SELECT * 
FROM EMP E
INNER JOIN DEPT D ON E.DEPTNO = D.DEPTNO; 


-- STUDENT, ENROL, SUBJECT
-- 1. 컴퓨터정보과의 평균보다 평균이 낮은 학과의 학과명, 점수 출력
SELECT * FROM STUDENT;
SELECT * FROM ENROL;
-- 답변 :
SELECT *
FROM (
    SELECT STU_DEPT, AVG(ENR_GRADE) AVG_GRADE
    FROM STUDENT S
    INNER JOIN ENROL E ON S.STU_NO = E.STU_NO
    GROUP BY STU_DEPT
)
WHERE AVG_GRADE < (
    SELECT AVG(ENR_GRADE) -- 69.4
    FROM STUDENT S
    INNER JOIN ENROL E ON S.STU_NO = E.STU_NO
    GROUP BY STU_DEPT
    HAVING STU_DEPT = '컴퓨터정보'
);
--
SELECT STU_DEPT, AVG(ENR_GRADE) AVG_GRADE
FROM STUDENT S
INNER JOIN ENROL E ON S.STU_NO = E.STU_NO
GROUP BY STU_DEPT;
--
SELECT AVG(ENR_GRADE) -- 69.4
FROM STUDENT S
INNER JOIN ENROL E ON S.STU_NO = E.STU_NO
GROUP BY STU_DEPT
HAVING STU_DEPT = '컴퓨터정보';
--
SELECT STU_DEPT, AVG(ENR_GRADE)
FROM STUDENT S
INNER JOIN ENROL E ON S.STU_NO = E.STU_NO
GROUP BY STU_DEPT;
--
SELECT *
FROM STUDENT S
INNER JOIN ENROL E ON S.STU_NO = E.STU_NO;

-- STU, PROFESSOR, DEPARTMENT
-- 1. 가장 많은 학생이 있는 학과와 가장 적은 학생이 있는 학과의 학과명, 학생수를 출력하시오.
SELECT * FROM STU;
SELECT * FROM DEPARTMENT;
--
SELECT DNAME, CNT
FROM DEPARTMENT D
INNER JOIN (
    SELECT DEPTNO1, COUNT(*) CNT
    FROM STU
    GROUP BY DEPTNO1
) T ON D.DEPTNO = T.DEPTNO1
WHERE CNT = (
    SELECT MAX(CNT)  --6
    FROM DEPARTMENT D
    INNER JOIN (
        SELECT DEPTNO1, COUNT(*) CNT
        FROM STU
        GROUP BY DEPTNO1
    ) T ON D.DEPTNO = T.DEPTNO1
)
--
UNION
SELECT DNAME, CNT
FROM DEPARTMENT D
INNER JOIN (
    SELECT DEPTNO1, COUNT(*) CNT
    FROM STU
    GROUP BY DEPTNO1
) T ON D.DEPTNO = T.DEPTNO1
WHERE CNT = (
    SELECT MIN(CNT)  --2
    FROM DEPARTMENT D
    INNER JOIN (
        SELECT DEPTNO1, COUNT(*) CNT
        FROM STU
        GROUP BY DEPTNO1
    ) T ON D.DEPTNO = T.DEPTNO1
);

--
SELECT MIN(CNT)  --2
FROM DEPARTMENT D
INNER JOIN (
    SELECT DEPTNO1, COUNT(*) CNT
    FROM STU
    GROUP BY DEPTNO1
) T ON D.DEPTNO = T.DEPTNO1;
--
SELECT MAX(CNT)  --6
FROM DEPARTMENT D
INNER JOIN (
    SELECT DEPTNO1, COUNT(*) CNT
    FROM STU
    GROUP BY DEPTNO1
) T ON D.DEPTNO = T.DEPTNO1;
--
SELECT *
FROM DEPARTMENT D
INNER JOIN (
    SELECT DEPTNO1, COUNT(*) CNT
    FROM STU
    GROUP BY DEPTNO1
) T ON D.DEPTNO = T.DEPTNO1;
--
SELECT DEPTNO1, COUNT(*)
FROM STU
GROUP BY DEPTNO1;

