-- PL/SQL
-- 사용자 정의 함수, 프로시저, 트리거

-- PL/SQL
-- 선언부(선택), 실행부, 예외처리(선택)
-- 마지막을 '/'로 마무리


-- 숫자를 2배로 돌려주는 함수 생성
CREATE OR REPLACE FUNCTION MULTI(I_VALUE IN NUMBER) --함수이름(매개변수 IN 타입)
RETURN NUMBER -- 리턴할 타입
IS 
-- 변수 선언
BEGIN
-- 실행부
    RETURN I_VALUE * 2;
END;
/
--
CREATE OR REPLACE FUNCTION MULTI(I_VALUE IN NUMBER)
RETURN NUMBER --리턴할 타입
IS

BEGIN
    RETURN I_VALUE * 2;
END;
/

--
SELECT ENR_GRADE, MULTI(ENR_GRADE)
FROM ENROL;
--
SELECT ENR_GRADE, MULTI(ENR_GRADE)
FROM ENROL;

-- DATE_FUNC 이름의 함수를 생성
SELECT 
    TO_CHAR(CDATETIME, 'YYYY-MM-DD HH24:MI:SS'),
    DATE_FUNC(CDATETIME)
FROM TBL_BOARD;
--
SELECT
    TO_CHAR(CDATETIME, 'YYYY-MM-DD HH24:MI:SS'),
    DATE_FUNC(CDATETIME)
FROM TBL_BOARD;
--
CREATE OR REPLACE FUNCTION DATE_FUNC(I_DATE IN DATE) --함수이름(매개변수 IN 타입)
RETURN VARCHAR2 --리턴할 타입
IS
BEGIN
    RETURN TO_CHAR(I_DATE, 'YYYY-MM-DD HH24:MI:SS'); --문자열 리턴
END;
/
--
CREATE OR REPLACE FUNCTION DATE_FUNC(I_DATE IN DATE)
RETURN VARCHAR2 -- 리턴할 타입
IS --변수 선언부
BEGIN
    RETURN TO_CHAR(I_DATE, 'YYYY-MM-DD HH24:MI:SS');
END;
/
--
SELECT
    B.*,
    DATE_FUNC(CDATETIME)
FROM TBL_BOARD B;
--
SELECT 
    B.*,
    DATE_FUNC(CDATETIME)
FROM TBL_BOARD B;
--
-- DATE_FUNC2(CDATETIME, 'DATETIME') -> 'YYYY-MM-DD HH24:MI:SS'
-- DATE_FUNC2(CDATETIME, 'DATE') -> 'YYYY-MM-DD'
-- DATE_FUNC2(CDATETIME, 'TIME') -> 'HH24:MI:SS'

-- DATE_FUNC2(CDATETIME, 'DATETIME') -> 'YYYY-MM-DD HH24:MI:SS'
-- DATE_FUNC2(CDATETIME, 'DATE') -> 'YYYY-MM-DD'
-- DATE_FUNC2(CDATETIME, 'TIME') -> 'HH24:MI:SS'

CREATE OR REPLACE FUNCTION DATE_FUNC2(I_DATE IN DATE, I_KEY IN VARCHAR2) --오버로딩
RETURN VARCHAR2 -- 리턴할 타입
IS
    O_DATE VARCHAR2(100); --변수선언 타입(크기)
BEGIN
    IF I_KEY = 'DATETIME' THEN
        O_DATE := TO_CHAR(I_DATE, 'YYYY-MM-DD HH24:MI:SS'); --변수에 담는다는 표시 => :=
    ELSIF I_KEY = 'DATE' THEN
        O_DATE := TO_CHAR(I_DATE, 'YYYY-MM-DD');
    ELSIF I_KEY = 'TIME' THEN
        O_DATE := TO_CHAR(I_DATE, 'HH24:MI:SS');
    ELSE 
        O_DATE := '값 잘못 입력했음';
    END IF;
    RETURN O_DATE;
END;
/
--
CREATE OR REPLACE FUNCTION DATE_FUNC2(I_DATE IN DATE, I_KEY IN VARCHAR2)
RETURN VARCHAR2
IS
    O_DATE VARCHAR2(100); --변수선언 타입(크기)
BEGIN
    IF I_KEY = 'DATETIME' THEN
        O_DATE := TO_CHAR(I_DATE, 'YYYY-MM-DD HH24:MI:SS');
    ELSIF I_KEY = 'DATE' THEN
        O_DATE := TO_CHAR(I_DATE, 'YYYY-MM-DD');
    ELSIF I_KEY = 'TIME' THEN
        O_DATE := TO_CHAR(I_DATE, 'HH24:MI:SS');
    ELSE
        O_DATE := '값을 잘못입력했음';
    END IF;
    RETURN O_DATE;
END;
/
--
SELECT
    DATE_FUNC2(CDATETIME, 'DATETIME') || ' ',
    DATE_FUNC2(CDATETIME, 'DATE') || ' ',
    DATE_FUNC2(CDATETIME, 'TIME')
FROM TBL_BOARD;


--
-- GRADE_FUNC
-- GRADE_FUNC(ENR_GRADE)
-- ENR_GRADE 값이 90 이상이면 'A' 리턴
-- ENR_GRADE 값이 80 이상이면 'B' 리턴
-- ENR_GRADE 값이 70 이상이면 'C' 리턴
-- ENR_GRADE 값이 60 이상이면 'D' 리턴
-- 그외는 'F' 리턴

SELECT * FROM ENROL;
--
SELECT ENR_GRADE, GRADE_FUNC(ENR_GRADE)
FROM ENROL;
--
SELECT 
    E.*,
    GRADE_FUNC(ENR_GRADE)
FROM ENROL E;

-- 답변 :
CREATE OR REPLACE FUNCTION GRADE_FUNC(I_SCORE IN NUMBER)
RETURN CHAR
IS
    --O_GRADE CHAR(1);
BEGIN
    IF I_SCORE > 100 OR I_SCORE < 0 THEN
        RETURN '잘못된 숫자 입력';
    ELSIF I_SCORE >= 90 THEN
        RETURN 'A';
    ELSIF I_SCORE >= 80 THEN
        RETURN 'B';
    ELSIF I_SCORE >= 70 THEN
        RETURN 'C';
    ELSIF I_SCORE >= 60 THEN
        RETURN 'D';
    ELSE 
        RETURN 'F';
    END IF;
    --RETURN O_GRADE;
END;
/
--
CREATE OR REPLACE FUNCTION GRADE_FUNC(I_SCORE IN NUMBER)
RETURN VARCHAR2
IS
BEGIN
    IF I_SCORE > 100 OR I_SCORE < 0 THEN
        RETURN '잘못된 숫자 입력';
    ELSIF I_SCORE >= 90 THEN
        RETURN 'A';
    ELSIF I_SCORE >= 80 THEN
        RETURN 'B';
    ELSIF I_SCORE >= 70 THEN
        RETURN 'C';
    ELSIF I_SCORE >= 60 THEN
        RETURN 'D';    
    ELSE 
        RETURN 'F';
    END IF;
END;
/
--
SELECT *
FROM STU;

-- GENDER_FUNC(JUMIN)
-- 7번째 숫자가 1, 3이면 '남자' 리턴
-- 2,4 면 '여자'리턴
-- 인자값이 13자리가 아니면 '제대로 값을 입력하세요' 리턴

--
SELECT 
    S.*,
    GENDER_FUNC(JUMIN)
FROM STU S;
--
CREATE OR REPLACE FUNCTION GENDER_FUNC(I_VALUE IN CHAR)
RETURN VARCHAR2
IS
    O_VALUE VARCHAR2(100);
BEGIN
    IF LENGTH(I_VALUE) != 13 THEN
        O_VALUE := '제대로 값을 입력하세요';
    END IF;
    IF SUBSTR(I_VALUE, 7, 1) IN ('1', '3') THEN
        O_VALUE := '남자';
    ELSIF SUBSTR(I_VALUE, 7, 1) IN ('2', '4') THEN
        O_VALUE := '여자';
    ELSE 
        O_VALUE := '해당없음';
    END IF;
    RETURN O_VALUE;
END;
/
--
CREATE OR REPLACE FUNCTION GENDER_FUNC(I_VALUE IN CHAR)
RETURN VARCHAR2
IS
    O_VALUE VARCHAR2(100); -- 왜 10으로하면안됨.? 너무 크기가 작은가봄
BEGIN
    IF LENGTH(I_VALUE) != 13 THEN
        RETURN '제대로 값을 입력하세요';
    END IF;
    IF SUBSTR(I_VALUE,7,1) IN (1,3) THEN 
        O_VALUE := '남자';
    ELSIF SUBSTR(I_VALUE,7,1) IN (2,4) THEN
        O_VALUE := '여자';
    ELSE 
        O_VALUE := '해당없음';
    END IF;
    RETURN O_VALUE;
END;
/
--
SELECT *
FROM STUDENT
WHERE STU_GENDER != 'M';