-- STUDENT, ENROL, SUBJECT

SELECT * FROM STUDENT; --STU_NO,STU_NAME,STU_DEPT,STU_GRADE,STU_CLASS,STU_GENDER,STU_HEIGHT, STU_WEIGHT
SELECT * FROM ENROL;--SUB_NO,STU_NO,ENR_GRADE
SELECT * FROM SUBJECT;--SUB_NO,SUB_NAME,SUB_PROF,SUB_GRADE,SUB_DEPT


-- 1. 학번, 학생이름, 학과, 시험과목명, 시험점수 출력
SELECT S.STU_NO, STU_NAME, STU_DEPT, SUB_NAME, ENR_GRADE
FROM STUDENT S
INNER JOIN ENROL E ON S.STU_NO = E.STU_NO
INNER JOIN SUBJECT SUB ON E.SUB_NO = SUB.SUB_NO;


-- 2. 각 학과별 시험 평균 점수 구하기(학과,평균점수 출력)
SELECT * FROM STUDENT; --STU_NO,STU_NAME,STU_DEPT,STU_GRADE,STU_CLASS,STU_GENDER,STU_HEIGHT, STU_WEIGHT
SELECT * FROM ENROL;--SUB_NO,STU_NO,ENR_GRADE
SELECT * FROM SUBJECT;--SUB_NO,SUB_NAME,SUB_PROF,SUB_GRADE,SUB_DEPT

SELECT STU_DEPT, AVG(ENR_GRADE)
FROM STUDENT S
INNER JOIN ENROL E ON S.STU_NO = E.STU_NO
GROUP BY STU_DEPT;



-- 3. 본인 학과의 시험 평균 점수보다 높은 평균 점수를 가진 학생의 학번, 이름, 평균점수 출력
SELECT * FROM STUDENT; --STU_NO,STU_NAME,STU_DEPT,STU_GRADE,STU_CLASS,STU_GENDER,STU_HEIGHT, STU_WEIGHT
SELECT * FROM ENROL;--SUB_NO,STU_NO,ENR_GRADE
SELECT * FROM SUBJECT;--SUB_NO,SUB_NAME,SUB_PROF,SUB_GRADE,SUB_DEPT
SELECT STU_DEPT, AVG(ENR_GRADE) DEPT_AVG  --STU_DEPT, DEPT_AVG
FROM STUDENT S
INNER JOIN ENROL E ON S.STU_NO = E.STU_NO
GROUP BY STU_DEPT;

SELECT S.STU_NO, STU_NAME, AVG(ENR_GRADE) PERSONAL__AVG_ENR_GRADE
FROM STUDENT S
INNER JOIN ENROL E ON S.STU_NO = E.STU_NO
INNER JOIN SUBJECT SUB ON E.SUB_NO = SUB.SUB_NO
GROUP BY S.STU_NO, STU_NAME
;

--SELECT *
SELECT STU_NO, STU_NAME, PERSONAL__AVG_ENR_GRADE
FROM (
    SELECT S.STU_NO, STU_NAME, STU_DEPT, AVG(ENR_GRADE) PERSONAL__AVG_ENR_GRADE
    FROM STUDENT S
    INNER JOIN ENROL E ON S.STU_NO = E.STU_NO
    INNER JOIN SUBJECT SUB ON E.SUB_NO = SUB.SUB_NO
    GROUP BY S.STU_NO, STU_NAME, STU_DEPT
) T1
INNER JOIN (
    SELECT STU_DEPT, AVG(ENR_GRADE) DEPT_AVG  --STU_DEPT, DEPT_AVG
    FROM STUDENT S
    INNER JOIN ENROL E ON S.STU_NO = E.STU_NO
    GROUP BY STU_DEPT    
) T2 ON T1.STU_DEPT = T2.STU_DEPT
WHERE PERSONAL__AVG_ENR_GRADE > DEPT_AVG;
















-- 4. 시험을 2번이상 본 학생의 학번, 이름, 시험본 횟수 출력   --시간없어서못품 ->품(+)

SELECT * FROM STUDENT; --STU_NO,STU_NAME,STU_DEPT,STU_GRADE,STU_CLASS,STU_GENDER,STU_HEIGHT, STU_WEIGHT
SELECT * FROM ENROL;--SUB_NO,STU_NO,ENR_GRADE


SELECT S.STU_NO, STU_NAME, COUNT(*) --행의개수
FROM ENROL E
INNER JOIN STUDENT S ON S.STU_NO = E.STU_NO
GROUP BY S.STU_NO, STU_NAME
HAVING COUNT(*) >= 2;

