-- ROWNUM   레코드(행)들에 넘버링

SELECT ROWNUM, S.*
FROM STUDENT S
ORDER BY STU_HEIGHT;


SELECT ROWNUM, S.*
FROM STUDENT S;
--WHERE ROWNUM <= 5;
--WHERE ROWNUM BETWEEN 3 AND 6; --이렇게 안됨.

SELECT ROWNUM, S.*
FROM STUDENT S
WHERE ROWNUM <= 5
ORDER BY STU_HEIGHT;


SELECT *
FROM STUDENT
WHERE STU_HEIGHT IS NOT NULL
ORDER BY STU_HEIGHT DESC;

--레코드를 붙이고, ROWNUM 이 붙음

SELECT *
FROM STUDENT
WHERE STU_HEIGHT IS NOT NULL
ORDER BY STU_HEIGHT DESC;



--
SELECT ROWNUM, S.*
FROM (
    SELECT *
    FROM STUDENT
    WHERE STU_HEIGHT IS NOT NULL
    ORDER BY STU_HEIGHT DESC
) S
WHERE ROWNUM <= 5;

-- 시험 평균 점수 상위 3명의 학번, 이름, 평균점수 출력
SELECT S.STU_NO, STU_NAME, AVG(ENR_GRADE) PERSONAL_ENR_GRADE_AVG
FROM STUDENT S
INNER JOIN ENROL E ON S.STU_NO = E.STU_NO
GROUP BY S.STU_NO, STU_NAME
ORDER BY PERSONAL_ENR_GRADE_AVG DESC;

--답변  : 위에서 ORDER BY 로 평균점수를 정렬해놓고, ROWNUM 적용하게 서브쿼리로 이용.
SELECT ROWNUM, S.*
FROM (
    SELECT S.STU_NO, STU_NAME, AVG(ENR_GRADE) PERSONAL_ENR_GRADE_AVG
    FROM STUDENT S
    INNER JOIN ENROL E ON S.STU_NO = E.STU_NO
    GROUP BY S.STU_NO, STU_NAME
    ORDER BY PERSONAL_ENR_GRADE_AVG DESC
) S
WHERE ROWNUM <= 3;

-- ROWNUM이 2번째인 학생  -> 서브쿼리로(+)

SELECT *
FROM (
    SELECT ROWNUM AS ROWZ, S.*
    FROM (
        SELECT S.STU_NO, STU_NAME, AVG(ENR_GRADE) PERSONAL_ENR_GRADE_AVG
        FROM STUDENT S
        INNER JOIN ENROL E ON S.STU_NO = E.STU_NO
        GROUP BY S.STU_NO, STU_NAME
        ORDER BY PERSONAL_ENR_GRADE_AVG DESC
    ) S
    WHERE ROWNUM <= 3
) WHERE ROWZ = 2;


SELECT ROWNUM AS ROWZ, S.*
FROM (
    SELECT S.STU_NO, STU_NAME, AVG(ENR_GRADE) PERSONAL_ENR_GRADE_AVG
    FROM STUDENT S
    INNER JOIN ENROL E ON S.STU_NO = E.STU_NO
    GROUP BY S.STU_NO, STU_NAME
    ORDER BY PERSONAL_ENR_GRADE_AVG DESC
) S
WHERE ROWNUM <= 3;


