-- SEQUENCE

CREATE SEQUENCE TEMP_SEQ  --SEQUENCE 생성시에는 '_SEQ'붙여주는게 낫긴함.(가독성)
    INCREMENT BY 1
    START WITH 1;
    --MINVALUE 1
    --MAXVALUE 99999
    --NOCYCLE; --99999 지나면 다시 순환할건지 - NOCYCLE은 순환안함.
    
DROP SEQUENCE TEMP_SEQ;

SELECT TEMP_SEQ.NEXTVAL  --조회할때마다 시퀀스가 1씩 올라감(INCREMENT BY 1)
FROM DUAL;

CREATE TABLE BOARD(
    BOARDNO NUMBER PRIMARY KEY,
    TITLE VARCHAR2(100),
    CONTENTS VARCHAR2(300),
    CDATETIME DATE,
    UDATETIME DATE
);
COMMIT;

INSERT INTO BOARD
VALUES(1, '첫번째 게시글', '안녕?', SYSDATE, SYSDATE);

ROLLBACK;

SELECT *
FROM BOARD;

CREATE SEQUENCE BOARD_SEQ
    INCREMENT BY 1
    START WITH 1;
    
INSERT INTO BOARD
VALUES(BOARD_SEQ.NEXTVAL, '333 게시글', '안녕?', SYSDATE, SYSDATE);

SELECT * FROM BOARD;

COMMIT;