-- TBL_EMP – 직원 정보 (SELF JOIN 가능: 상사 관계)
-- TBL_DEPT – 부서 정보
-- TBL_PROJECT – 프로젝트 정보
-- TBL_ASSIGNMENT – 직원이 프로젝트에 배정된 정보

SELECT * FROM TBL_EMP;
SELECT * FROM TBL_DEPT;  
SELECT * FROM TBL_PROJECT;
SELECT * FROM TBL_ASSIGNMENT;

-- 5. 각 부서별 평균 금여를 구한 후 평균 급여를 기준으로 내림차순 하시오. ( 10점 )
-- 사용테이블 : TBL_EMP, TBL_DEPT
-- 출력 컬럼 : 부서 이름, 평균 급여

SELECT * FROM TBL_EMP;
SELECT * FROM TBL_DEPT;
-- 답변 :
SELECT DEPT_NAME, AVG(SALARY)SAL
FROM TBL_EMP E
INNER JOIN TBL_DEPT D ON E.DEPT_ID = D.DEPT_ID
GROUP BY DEPT_NAME
ORDER BY SAL DESC;
--
SELECT DEPT_NAME, AVG(SALARY)
FROM TBL_EMP E
INNER JOIN TBL_DEPT D ON E.DEPT_ID = D.DEPT_ID
GROUP BY DEPT_NAME;
--
SELECT *
FROM TBL_EMP E
INNER JOIN TBL_DEPT D ON E.DEPT_ID = D.DEPT_ID;

-- 6. 모든 부서장들의 급여 평균보다 높은 급여를 받는 직원들을 출력하시오. ( 10점 )
-- 사용 테이블 : TBL_EMP, TBL_DEPT
-- 출력 컬럼 : 직원 이름, 급여, 부서장들의 평균 급여(+)-INNER JOIN

SELECT * FROM TBL_EMP;
SELECT * FROM TBL_DEPT;
--
SELECT EMP_NAME, SALARY, AVG_SAL
FROM TBL_EMP E
INNER JOIN (
    SELECT AVG(SALARY) AVG_SAL --8566667
    FROM TBL_DEPT D
    INNER JOIN TBL_EMP E ON D.HEAD_ID = E.EMP_ID
) T ON E.SALARY > T.AVG_SAL;   -- **컬럼이 1개인것도 INNERJOIN 가능!
-- 
SELECT * 
FROM TBL_EMP E
INNER JOIN (
    SELECT AVG(SALARY) AVG_SAL --8566667
    FROM TBL_DEPT D
    INNER JOIN TBL_EMP E ON D.HEAD_ID = E.EMP_ID
) T ON E.SALARY > T.AVG_SAL;   -- 컬럼이 1개인것도 INNERJOIN 가능!
--
SELECT * 
FROM TBL_EMP E
INNER JOIN (
    SELECT AVG(SALARY) AVG_SAL --8566667
    FROM TBL_DEPT D
    INNER JOIN TBL_EMP E ON D.HEAD_ID = E.EMP_ID
) T ON 1=1;--TRUE  --꿀팁(+)        조건이 항상 TRUE가 되게 할수도있음!
--WHERE SALARY > AVG_SAL;  --TRUE
--
SELECT *
FROM TBL_EMP
WHERE SALARY > (
    SELECT AVG(SALARY) AVG_SAL--8566667
    FROM TBL_DEPT D
    INNER JOIN TBL_EMP E ON D.HEAD_ID = E.EMP_ID
);
--
SELECT AVG(SALARY) AVG_SAL --8566667
FROM TBL_DEPT D
INNER JOIN TBL_EMP E ON D.HEAD_ID = E.EMP_ID;
--
SELECT *
FROM TBL_DEPT D
INNER JOIN TBL_EMP E ON D.HEAD_ID = E.EMP_ID;

-- 7. '모바일 앱 개발' 프로젝트에 배정된 직원들중 가장 높은 급여를 받는 직원을 출력하시오. ( 5점 )
-- 사용 테이블 : TBL_EMP, TBL_PROJECT, TBL_ASSIGNMENT
-- 출력 컬럼 : 직원 이름, 직급, 급여

SELECT * FROM TBL_EMP;
SELECT * FROM TBL_PROJECT;
SELECT * FROM TBL_ASSIGNMENT;
--
SELECT EMP_NAME, JOB_TITLE, SALARY
FROM TBL_PROJECT P
INNER JOIN TBL_ASSIGNMENT A ON P.PROJ_ID = A.PROJ_ID
INNER JOIN TBL_EMP E ON A.EMP_ID = E.EMP_ID
WHERE PROJ_NAME = '모바일 앱 개발' AND SALARY = (           --조건이 두개 => AND 로 연결(+)
    SELECT MAX(SALARY)   -- 6700000
    FROM (
        SELECT EMP_NAME, JOB_TITLE, SALARY
        FROM TBL_PROJECT P
        INNER JOIN TBL_ASSIGNMENT A ON P.PROJ_ID = A.PROJ_ID
        INNER JOIN TBL_EMP E ON A.EMP_ID = E.EMP_ID
        WHERE PROJ_NAME = '모바일 앱 개발'
    )
);
--
SELECT MAX(SALARY)   -- 6700000
FROM (
    SELECT EMP_NAME, JOB_TITLE, SALARY
    FROM TBL_PROJECT P
    INNER JOIN TBL_ASSIGNMENT A ON P.PROJ_ID = A.PROJ_ID
    INNER JOIN TBL_EMP E ON A.EMP_ID = E.EMP_ID
    WHERE PROJ_NAME = '모바일 앱 개발'
);

--
SELECT EMP_NAME, JOB_TITLE, SALARY
FROM TBL_PROJECT P
INNER JOIN TBL_ASSIGNMENT A ON P.PROJ_ID = A.PROJ_ID
INNER JOIN TBL_EMP E ON A.EMP_ID = E.EMP_ID
WHERE PROJ_NAME = '모바일 앱 개발';
--
SELECT *
FROM TBL_PROJECT P
INNER JOIN TBL_ASSIGNMENT A ON P.PROJ_ID = A.PROJ_ID
INNER JOIN TBL_EMP E ON A.EMP_ID = E.EMP_ID
WHERE PROJ_NAME = '모바일 앱 개발';

-- 8. 각 직원의 부하직원의 수(자신의 emp_id를 manager_id로 가지고 있는 사람 수)를 구하시오. 단, 없으면 0으로 출력하시오. ( 5점 )
-- 사용 테이블 : TBL_EMP
-- 출력 컬럼 : 직원 이름, 직급, 부하직원 수
--
SELECT * FROM TBL_EMP;
-- 선생님풀이(+)
SELECT E1.EMP_NAME, E1.JOB_TITLE, COUNT(E2.EMP_ID)
FROM TBL_EMP E1
LEFT JOIN TBL_EMP E2 ON E1.EMP_ID = E2.MANAGER_ID
GROUP BY E1.EMP_NAME, E1.JOB_TITLE;
--
SELECT E1.EMP_NAME, E1.JOB_TITLE, COUNT(E2.MANAGER_ID)  --**COUNT(NULL값) => 0으로 나온다.
FROM TBL_EMP E1
LEFT JOIN TBL_EMP E2 ON E1.EMP_ID = E2.MANAGER_ID
GROUP BY E1.EMP_NAME, E1.JOB_TITLE ;
--
SELECT *
FROM TBL_EMP E1
LEFT JOIN TBL_EMP E2 ON E1.EMP_ID = E2.MANAGER_ID;
--
SELECT *
FROM TBL_EMP E1
LEFT JOIN TBL_EMP E2 ON E1.EMP_ID = E2.MANAGER_ID;
--
SELECT * FROM TBL_EMP;
--
SELECT EMP_NAME, JOB_TITLE, NVL(CNT, 0)
FROM TBL_EMP E
LEFT JOIN (                        -- LEFT JOIN 으로 왼쪽테이블에 있는거는 꼭 나오게 하고 나머지는 NULL로 나오게 할수있음
    SELECT MANAGER_ID, COUNT(*) CNT
    FROM TBL_EMP
    GROUP BY MANAGER_ID
    HAVING MANAGER_ID IS NOT NULL
) T ON E.EMP_ID = T.MANAGER_ID;

--
SELECT *
FROM TBL_EMP E
LEFT JOIN (
    SELECT MANAGER_ID, COUNT(*) CNT
    FROM TBL_EMP
    GROUP BY MANAGER_ID
    HAVING MANAGER_ID IS NOT NULL
) T ON E.EMP_ID = T.MANAGER_ID;   -- LEFT JOIN 으로 왼쪽테이블에 있는거는 꼭 나오게 하고 나머지는 NULL로 나오게 할수있음
--
SELECT MANAGER_ID, COUNT(*)
FROM TBL_EMP
GROUP BY MANAGER_ID
HAVING MANAGER_ID IS NOT NULL;